### ISSUE TITLE
how to persist cache to something like localStorage/sessionStorage over days

### ISSUE THREAD

**Issue by johnnliu** [timdeschryver/rx-query#13]
question - how would I go about persisting the cache to localStorage over (a few) days?

**Comment by timdeschryver** [comment]
Hi @johnnliu , this isn't something that rx-query provides and I think that it shouldn't be.
Since the cache is a stream, I you can hook into it and build up a local storage cache.
When the app starts you can make use of the `mutateSuccess` helper (perhaps that we need a new helper for this) to rehydrate the cache.
