### ISSUE TITLE
Feature request: switch off auto-updates

### ISSUE THREAD

**Issue by IanIsFluent** [timdeschryver/rx-query#15]
As we work with forms a lot, the auto-refresh behaviour is not what we need. I don't want the data in the user's fields to be updated while they have the page open!

An option to turn off all background updates would be lovely! Especially the refetch time, which doesn't currently seem to be possible to switch off (but is set to MAX_VALUE)!?

What _would_ be useful would be a notification that there's new data available (ideally already prefetched 😍), so we could add a toast with a button to update the data?

**Comment by timdeschryver** [comment]
You can set the config (when it has to refresh) for each query individually (or at a global level with `setQueryConfig`.

```ts
setQueryConfig({
	refetchOnWindowFocus: false,
	retries: 0,
	cacheTime: 60_000,
});
```

I believe I went for `MAX_VALUE` because I saw this was being used in react-query (or RxJS), but it isn't anymore.

Now, when I give it another look I agree that that seems weird, so this will be changed to `Infity`.

I don't think "pausing" the refresh should be the provided by rx-query, but I'm open for feedback and contributions.
Feel free to create a Pull Request and we can discuss it further there, or we could discuss it in this issue before creating a Pull Request.

**Comment by IanIsFluent** [comment]
> You can set the config (when it has to refresh) for each query individually (or at a global level with `setQueryConfig`.
> 
> ```ts
> setQueryConfig({
> 	refetchOnWindowFocus: false,
> 	retries: 0,
> 	cacheTime: 60_000,
> });
> ```

Oo, that's lovely, I hadn't seen that! Did I fail to read the docs properly? Infinity is interesting... I'd have expected 0 - and for that to have the meaning of 'never'? (I actually set it to that, assuming it'd work, and it filled up the network tab pretty quickly!)

I *think* if you could use 0 to disable it, that *might* also fix: https://github.com/timdeschryver/rx-query/issues/17 ?

**Comment by timdeschryver** [comment]
You didn't miss is in the docs, I'm adding it in #18.
Setting the config to `Infity` actually disables the refreshing time.

**Comment by IanIsFluent** [comment]
> You didn't miss is in the docs, I'm adding it in #18.
> Setting the config to `Infity` actually disables the refreshing time.

OK, thats good! I wonder if I could use an override config for the tests in a `beforeAll()` so it never refreshes - and therefore the tests will finish? 🤔

**Comment by timdeschryver** [comment]
Yea, that could work if you're not overriding it in specific queries.
