### ISSUE TITLE
The difference between cacheTime and staleTime is unclear.

### ISSUE THREAD

**Issue by brandonpittman** [timdeschryver/rx-query#25]
It's a little unclear how the cacheTime and staleTime options work together.

If the staleTime is after a trigger, the cache is returned? Is that's so, then what's the purpose of the cacheTime?

More clarification in the docs would avoid this confusion.

**Comment by salmin89** [comment]
Hey,
I just recently learned this framework but I found that the documentation from:
[react-query](https://react-query.tanstack.com/guides/important-defaults) is a bit more helpful for some of the configuration-options.

staleTime is a cache for something that is currently mounted. Once staleTime expires it will force a refetch.

cacheTime is a cache for something that is no longer mounted. If you have something very page-specific you can have a low cacheTime because once the user leaves that page, you would want that cache garbage collected

**Comment by timdeschryver** [comment]
Thanks for answering this @salmin89 , this is spot on.
