### ISSUE TITLE
Help Wanted / In need of more examples / documentation

### ISSUE THREAD

**Issue by salmin89** [timdeschryver/rx-query#26]
Hey Tim!

I am struggling with understanding how I am suppose to use the mutation when updating an item from an array. In your example you have a query that reads 1 person, and updates that 1 person. The id is hard-coded as well.

Any chance you can setup a full CRUD example? I usually use https://mockapi.io/ as a public demo-api

Alternatively - can you look at my example and explain if there is something I'm missing. The example is fully working but I feel like I'm using a lot of boilerplate to set it up.
https://stackblitz.com/edit/rx-query-crud-demo?file=src/sample.service.ts

**Comment by salmin89** [comment]
After some more testing and finding this old [blog](https://timdeschryver.dev/blog/the-benefits-of-adding-rx-query-to-your-angular-project) I think I understand how I'm supposed to use mutation.

Here is my attempt #2 at making CRUD operators work rx-query:
https://stackblitz.com/edit/rx-query-demo-2?file=src/app/app.component.ts

If someone can review and give me inputs on how to reduce boilerplate and repetitive code - let me know

**Comment by timdeschryver** [comment]
The second attempt is how I envisioned it to work.
I think the API of rx-query could be better when it comes to mutators though.

I also want to inform you that I've put this project on the back burner lately.
Because it seemed that react-query, was making efforts to make it cross-framework compatible. 
While rx-query works in its current state, it might be good to keep in mind 🙂
Instead, I've been using an [RxJS echo operator](https://gist.github.com/timdeschryver/6648ce214d5f187fb46e30d3ae734c11#file-echo-ts), combined with NgRx to refresh my stale data.
