### ISSUE TITLE
documentation request for best practices using this lib

### ISSUE THREAD

**Issue by mikelgo** [timdeschryver/rx-query#31]
Hi,

first of all thank you for providing this amazing lib. 

In order to further improve the docs (at least I) would be happy about a section for best practices using `rx-query`. Eg. something like:

- how to organize the keys for queries
- manual refresh or relying on automatic refresh (refetshInterval, refetchOnWindowFocus)
and probably there are many more points. Pretty sure that especially you implicitly apply some best practices naturally when using the lib. 

Also maybe a section about integrations with different frameworks would be interesting. I understand `rx-query` as layer on top of `rxjs`. So everybody using `rxjs` is at the end the target audience, but I guess main intention comes from Angular? I guess this lib is also a great fit together with NgRx. 

What do you think?

**Comment by timdeschryver** [comment]
Hi @mikelgo thanks for the feedback.
I'm not really maintaining this library anymore, if you want to create the docs that's fine by me, and I will review the PR. A lot can be taken from react-query, because this library was based on that.

Yes, the main intention was aimed to Angular (and can be used together with NgRx), but it can also be used with different frameworks. For a more Angular aimed alternative, you can also refer to [ngx-query-state](https://github.com/timdeschryver/query-state).
