### ISSUE TITLE
Cannot read property 'cacheTime' of undefined when calling refreshQuery("key", param)

### ISSUE THREAD

**Issue by berthertogen** [timdeschryver/rx-query#7]
# Expected Behavior
The list of posts is filled with post of the userId 2
# Current Behavior
 `Cannot read property 'cacheTime' of undefined` appear in the console and the list is not refreshed
# Possible Solution
/
# Steps to Reproduce
Demo: https://stackblitz.com/edit/angular-ivy-7mkdbu?file=src/app/hello.component.ts
# Context (Environment)
/
# Detailed Description
When calling the refreshQuery for a key with new parameters a call to the backend should be made and the new value should be put on the observable pipeline.
# Possible Implementation
/

**Comment by alexkunin** [comment]
Apparently the following is missing:

* a note in docs that `refreshQuery()` expects same key *and* parameters; in this particular case userId must be the same, so, if I modify demo to have `2` as `userId` in both `query()` and `refreshQuery()` calls, it works just fine; maybe whole conception of query keys and its interaction with query parameters needs some in-depth explanations.
* a check in the code that will throw a meaningful exception;
* maybe a special mode for `refreshQuery()` -- if no parameters are given, refresh most recent query with the same key and whatever parameter was used at that time; but this might add unnecessary complication to API; I'd say it is a reasonable statement that if your particular component wants to have results for many users, it might be having too much of responsibility (this is subjective, of course).

**Comment by berthertogen** [comment]
Ok, thanks for the clear explanation! I modified the example to have some static list and update & refresh this list on button click.
Now the list for userId 1 is updated and the new value is added.

I'll see if I can create a PR to make its usage clear in the docs :)

**Comment by timdeschryver** [comment]
It shouldn't throw an exception, so that's a bug. 

As @alexkunin mentioned, this isn't the use case of `refreshQuery`. 
It's here to refresh existing data in the cache. 
An example where you can use use this is a refresh button, or when you save the data and want a refresh afterwards. Take a look at the [prefetch example](https://timdeschryver.github.io/rx-query/?path=/story/rx-query--prefetch) or at the [prefetch code](https://github.com/timdeschryver/rx-query/blob/master/src/examples/prefetch.component.ts) for an example.

To load the data for userId `2`, you will have refactor the static id to a stream.
For example:

```ts
userId = new Subject<number>();
//                            👇 id here is value of the stream
data$ = query('key', userId, (id) => http.get(id));

// get data for user 1
userId.next(1) 

// get data for user 2
userId.next(2) 
``` 

Take a look at the [pagination example](https://timdeschryver.github.io/rx-query/?path=/story/rx-query--pagination) or at the [pagination code](https://github.com/timdeschryver/rx-query/blob/master/src/examples/pagination.component.ts) for an example.


The docs for these "helpers" are missing tho...

**Comment by timdeschryver** [comment]
Version 0.0.13 includes a fix for `Cannot read property 'cacheTime' of undefined`. (See #9 for more info)
Thanks for the docs PR @berthertogen , I'll take a look at it soon.

**Comment by berthertogen** [comment]
A small remark on my situation, I was dealing with `Observable<{email:string, term: string}>` as parameter, I tried to simplify the demo :). I've added a `withLatestFrom(this.params$)` to my service call that does the mutation and called the refreshQuery with these parameters, and its working!.
```ts
        this.subscriptionService.create(output.subscription)
          .pipe(
            first(),
            tap(_ => this.snackBarService.send(`Je hebt ${output.subscription.team} ingeschreven voor ${output.quiz.title}`)),
            withLatestFrom(this.params$),
            tap(params => refreshQuery("quizzes", params[1]))
          ).subscribe();
```

Thank you both for the clear explanation
